gsap.from(".left",{
    x:-300,
    opacity:0,
    duration:1
})
gsap.from(".right",{
    x:200,
    opacity:0,
    duration:1
})
gsap.from(".rightSection",{
    x:200,
    opacity:0,
    duration:1
})